#!/usr/bin/env php
<?php

const BASE_DIR = __DIR__;

require_once BASE_DIR.'/vendor/autoload.php';

$container = require_once BASE_DIR.'/application/config/console.php';

$console = $container->get('console');
$console->run();


